export const SKILLS = ['Photography', 'Guitar', 'Web design', 'Coding', 'Japanese', 'Drawing', 'Ceramics', 'Public speaking', 'Video editing', 'Piano', 'Chess', 'Home cooking', 'Gardening', 'Bike repair', 'Sewing', 'Astronomy', 'Printmaking'];
export const CATEGORIES = ['All skills', 'Music', 'Art & design', 'Technology', 'Languages', 'Everyday skills'];
export const CATEGORY = { Photography: 'Art & design', Guitar: 'Music', 'Web design': 'Technology', Coding: 'Technology', Japanese: 'Languages', Drawing: 'Art & design', Ceramics: 'Art & design', 'Public speaking': 'Everyday skills', 'Video editing': 'Technology', Piano: 'Music', Chess: 'Everyday skills' };
Object.assign(CATEGORY, { 'Home cooking': 'Everyday skills', Gardening: 'Everyday skills', 'Bike repair': 'Everyday skills', Sewing: 'Art & design', Astronomy: 'Everyday skills', Printmaking: 'Art & design' });
// Every person below is fictional. No remote profiles or messages are used.
export const PEOPLE = [
 { id: 'maya', name: 'Maya R.', teach: 'Guitar', learn: 'Photography', title: 'Three chords. Your first song.', outcome: 'Play G, C and D, then put them together in a simple song.', bio: 'I remember how strange the first chord felt. We will take it slowly, one string at a time.', level: 'Beginner', duration: 30, need: 'A guitar and a little patience.', tint: 'sand' },
 { id: 'alex', name: 'Alex M.', teach: 'Web design', learn: 'Japanese', title: 'A page you can call your own.', outcome: 'Build a small personal page with HTML and CSS.', bio: 'I like turning a blank browser into something useful. Bring an idea and we will make a first version together.', level: 'Beginner', duration: 45, need: 'A laptop with a browser and a text editor.', tint: 'blue' },
 { id: 'sam', name: 'Sam K.', teach: 'Coding', learn: 'Photography', title: 'Make your first little program.', outcome: 'Write a short Python quiz and understand how it works.', bio: 'Small projects are my favourite way to learn. We will write the code together and leave time for questions.', level: 'Beginner', duration: 30, need: 'A laptop and a browser-based Python editor.', tint: 'mint' },
 { id: 'priya', name: 'Priya S.', teach: 'Guitar', learn: 'Coding', title: 'Find your rhythm.', outcome: 'Learn a steady strumming pattern and one chord change.', bio: 'You do not need to read music. We will work on a simple rhythm you can practise afterwards.', level: 'Beginner', duration: 30, need: 'A tuned acoustic or electric guitar.', tint: 'rose' },
 { id: 'noah', name: 'Noah L.', teach: 'Photography', learn: 'Guitar', title: 'See the light differently.', outcome: 'Make three portraits using window light and your phone.', bio: 'A good photo starts with noticing. We will explore light, framing and the camera you already have.', level: 'Beginner', duration: 45, need: 'A phone camera and a nearby window.', tint: 'blue' },
 { id: 'hana', name: 'Hana T.', teach: 'Japanese', learn: 'Web design', title: 'Your first conversation.', outcome: 'Introduce yourself and ask three simple questions in Japanese.', bio: 'We will practise speaking together, with useful phrases you can keep and revisit.', level: 'Beginner', duration: 30, need: 'Something to take notes with.', tint: 'rose' },
 { id: 'leah', name: 'Leah W.', teach: 'Drawing', learn: 'Photography', title: 'Turn looking into drawing.', outcome: 'Sketch an everyday object using simple shapes and shading.', bio: 'You do not need expensive materials or a perfect first sketch. Just start with what is in front of you.', level: 'Beginner', duration: 30, need: 'Paper, a pencil and an everyday object.', tint: 'sand' },
 { id: 'luca', name: 'Luca B.', teach: 'Ceramics', learn: 'Drawing', title: 'Make a little clay cup.', outcome: 'Shape and finish a small pinch pot with air-dry clay.', bio: 'Making things by hand is a lovely change of pace. We will learn a simple technique and make it your own.', level: 'Beginner', duration: 45, need: 'Air-dry clay, water and a protected work surface.', tint: 'mint' },
 { id: 'amara', name: 'Amara J.', teach: 'Public speaking', learn: 'Guitar', title: 'Find your voice.', outcome: 'Prepare and deliver a clear one-minute introduction.', bio: 'We will focus on one idea, a calm opening and a confident ending, with kind feedback.', level: 'Beginner', duration: 30, need: 'An idea you would enjoy speaking about.', tint: 'rose' },
 { id: 'owen', name: 'Owen C.', teach: 'Video editing', learn: 'Web design', title: 'Tell a story in 30 seconds.', outcome: 'Arrange a few clips into a short video with a beginning and an ending.', bio: 'Editing is about choices. We will work with a few clips and make every cut earn its place.', level: 'Beginner', duration: 45, need: 'A few video clips and a free editing app.', tint: 'blue' },
 { id: 'zoe', name: 'Zoe F.', teach: 'Piano', learn: 'Photography', title: 'A melody at your fingertips.', outcome: 'Find the notes and play a simple melody with one hand.', bio: 'We will start with the keyboard layout and move at your pace. No music-reading experience needed.', level: 'Beginner', duration: 30, need: 'A piano, keyboard or virtual keyboard.', tint: 'mint' },
 { id: 'ishaan', name: 'Ishaan M.', teach: 'Chess', learn: 'Piano', title: 'Think one move ahead.', outcome: 'Learn how the pieces move and practise a short opening.', bio: 'I enjoy the moment a pattern clicks. We will play through examples and talk about our choices.', level: 'Beginner', duration: 30, need: 'A chessboard or a free online board.', tint: 'sand' }
 ,{ id: 'farid', name: 'Farid A.', teach: 'Home cooking', learn: 'Sewing', title: 'Flatbread, from flour to first bite.', outcome: 'Mix a small dough, feel when it is ready and roll two flatbreads.', bio: 'I learned by watching my family cook. We will work with a simple recipe and talk about texture, resting time and what to try next.', level: 'Beginner', duration: 45, need: 'Flour, water, a bowl, a rolling pin and a clear work surface. Discuss ingredients and allergies before planning.', tint: 'sand' }
 ,{ id: 'ruth', name: 'Ruth E.', teach: 'Gardening', learn: 'Home cooking', title: 'One cutting. A new plant.', outcome: 'Take a soft-stem cutting, prepare a pot and make a care plan for the first week.', bio: 'My garden started with a cutting from a neighbour. Bring a plant you can identify and we will find a sensible starting point.', level: 'Beginner', duration: 30, need: 'A suitable plant, clean scissors, a small pot and potting mix.', tint: 'mint' }
 ,{ id: 'mei', name: 'Mei C.', teach: 'Bike repair', learn: 'Gardening', title: 'Get your wheel turning again.', outcome: 'Remove an inner tube, locate a puncture and practise fitting a replacement.', bio: 'We will learn the parts before reaching for tools. Brake or structural problems need a qualified repair professional; this lesson focuses on a basic puncture.', level: 'Beginner', duration: 45, need: 'A bicycle, tyre levers, a compatible inner tube and a pump.', tint: 'blue' }
 ,{ id: 'ada', name: 'Ada O.', teach: 'Sewing', learn: 'Printmaking', title: 'Keep the jacket. Mend the pocket.', outcome: 'Thread a needle, practise a running stitch and secure a small fabric patch.', bio: 'Visible mending gives worn clothes a new chapter. We will practise on scrap fabric before working on your garment.', level: 'Beginner', duration: 45, need: 'A needle, thread, fabric scissors and a scrap of cotton.', tint: 'rose' }
 ,{ id: 'marisol', name: 'Marisol V.', teach: 'Astronomy', learn: 'Chess', title: 'Find your way around the night sky.', outcome: 'Read a simple sky chart and locate two visible constellations for your location.', bio: 'You do not need a telescope to begin. We will plan a short observing session and learn what to look for before going outside.', level: 'Beginner', duration: 30, need: 'A sky chart for your location, warm clothing and a dim red torch. Choose a safe, accessible place.', tint: 'blue' }
 ,{ id: 'moana', name: 'Moana P.', teach: 'Printmaking', learn: 'Japanese', title: 'Roll the ink. Reveal the print.', outcome: 'Make a simple monoprint using a reusable plate and two colours.', bio: 'Printing makes room for surprises. We will explore pressure and ink coverage using simple shapes and a washable setup.', level: 'Beginner', duration: 45, need: 'Water-based printing ink, a smooth plate, a roller, paper and an apron.', tint: 'sand' }
];
